import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";
import "./globals.css";

const inter = Golos_Text({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#191919]`}>{children}</body>
    </html>
  );
}
